stages:
  - format
  - build

format-job:
  stage: format
  image: golang:1.23-alpine
  cache:
    key: go-mod
    paths:
      - /go/pkg/mod
  script:
    - go env -w GOPROXY=direct
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
  allow_failure: false

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
