stages:
  - format
  - build

format-job:
  stage: format
  image: golang:1.23-alpine
  cache:
    key: go-mod
    paths:
      - /go/pkg/mod
  script:
    - export HTTP_PROXY=$SOCKS_PROXY
    - export HTTPS_PROXY=$SOCKS_PROXY
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
  allow_failure: false

build-job:
  stage: build
  script:
    - echo "Hello, $CI_PROJECT_NAME!"
    - export HTTP_PROXY=$SOCKS_PROXY
    - export HTTPS_PROXY=$SOCKS_PROXY
    - docker build --build-arg HTTP_PROXY=$SOCKS_PROXY --build-arg HTTPS_PROXY=$SOCKS_PROXY -t $CI_PROJECT_NAME:latest .
    - docker save -o $CI_PROJECT_NAME.tar.gz $CI_PROJECT_NAME:latest
    - ls /image
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days