apiVersion: v2
name: go-api-helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: "13.6.6"  # Use the latest stable version
    repository: "https://charts.bitnami.com/bitnami"