apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: todo
  namespace: todo

data:
  DATABASE_URL: "mongodb://root:root_Password@mongo-0.mongodb:27017,mongo-1.mongodb:27017/?replicaSet=rs0&retryWrites=true&w=majority"
  DATABASE_DB: "todo"
  DATABASE_COLLECTION: "todo"