apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-api-helm.fullname" . }}
  labels:
    {{- include "go-api-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-api-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-api-helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "go-api-helm.name" . | printf "%s-config" | quote }}
                  key: DATABASE_DB
            - name: DATABASE_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "go-api-helm.name" . | printf "%s-config" | quote }}
                  key: DATABASE_COLLECTION
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "go-api-helm.name" . | printf "%s-config" | quote }}
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "go-api-helm.name" . | printf "%s-secret" | quote }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "go-api-helm.name" . | printf "%s-secret" | quote }}
                  key: DATABASE_PASSWORD
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
