apiVersion: v1
kind: Secret
metadata:
  name: {{include "go-api-helm.name" . | printf "%s-secret" | quote}}
  labels:
    {{- include "go-api-helm.labels" . | nindent 4}}
type: Opaque
data:
  DATABASE_PASSWORD: {{.Values.mongodb.auth.rootPassword | b64enc | quote}}
  DATABASE_USERNAME: {{.Values.mongodb.auth.rootUser | b64enc | quote}}